### ISSUE TITLE
Image upload for person profile pics

### ISSUE THREAD

**Issue by mgschoen** [mgschoen/peer-group-network#1]

**Comment by mgschoen** [comment]
# Subissues

### Backend
- [x] setup loopback-component-storage
- [x] allow only .jpg and .jpeg filetypes
- [x] automatically resize large images on upload

### Frontend
- [x] show image preview in edit dialog
- [ ] replace image url input field with a file selector (always upload new file)
- [ ] file manager for selecting already uploaded files and deleting them
